### PR TITLE
fix: Remove Admonition code block from search results

### LINKED ISSUE #2369: Exclude the “Admonition” block from search preview

### PR DESCRIPTION
**Pull request by nilubava**
## What issue does this fix?

Fixes #2369

### CODE REVIEW

File: src/utils/algolia.js [hunk 1]
```diff
@@ -53,7 +53,9 @@ const handleRawBody = (node) => {
         !section.includes('cmdResult>') &&
         !section.includes('<Subsections') &&
         !section.includes('cmd>') &&
-        !section.includes('<!-- prettier-ignore -->')
+        !section.includes('<!-- prettier-ignore -->') &&
+        !section.includes('<Admonition type="warning">') &&
+        !section.includes('</Admonition>')
```
Comment (janpio) [inline src/utils/algolia.js:58]: This only removes these explicit lines, not the content of the whole block, correct @nilubava?
