### PR TITLE
fix: remove frontmatter + zindex for footer button

### LINKED ISSUE #4694: Feedback z-index overlap
After leaving positive feedback by pressing like button in the end of the page, "Subscribe for updates" button from newsletter section overlaps feedback popup. I'm using Chrome 112

image

### PR DESCRIPTION
**Pull request by nilubava**
#4694 
#1341

### CODE REVIEW

File: src/components/layout.tsx [hunk 1]
```diff
@@ -45,7 +45,7 @@ const Content = styled.article<{ fullWidth?: boolean; wide?: boolean }>`
       : 'max-width: 748px;'}
   flex: 1;
   position: relative;
-  z-index: 100;
+  z-index: 1001;
```
Comment (Jolg42) [inline src/components/layout.tsx:48]: Mentioned in Slack: I think this PR might have broken the search on the website/docs, see screenshot (changing the z-index back to old value fixes it) 
Screenshot 2023-06-07 at 14 33 58
